# Generated by Django 4.2.11 on 2026-04-13 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='from_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='assets.room'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='to_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='assets.room'),
        ),
        migrations.AddField(
            model_name='assetsequence',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.campus'),
        ),
        migrations.AddField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.campus'),
        ),
        migrations.AddField(
            model_name='asset',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.room'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('floor', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('building', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('campus', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='assetsequence',
            unique_together={('campus', 'asset_type_code')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_id'], name='assets_asse_asset_i_501f65_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_asse_status_347ce9_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_type'], name='assets_asse_asset_t_529092_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['campus'], name='assets_asse_campus__b6e4ba_idx'),
        ),
    ]
