# Generated by Django 4.2.11 on 2026-04-20 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0002_initial'),
        ('assets', '0003_budget_budgettransaction_assetwarranty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('CHECKOUT', 'Checkout'), ('RETURN', 'Return'), ('MAINTENANCE_REQUEST', 'Maintenance Request'), ('MAINTENANCE_COMPLETE', 'Maintenance Complete'), ('CONDITION_CHANGE', 'Condition Change'), ('TRANSFER', 'Transfer'), ('ASSIGNMENT', 'Assignment')], max_length=30)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('event_data', models.JSONField(default=dict)),
                ('description', models.TextField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_events', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assets.asset')),
                ('related_checkout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='assets.assetcheckout')),
                ('related_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='maintenance.maintenancerequest')),
                ('related_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='assets.assettransfer')),
            ],
            options={
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['asset'], name='assets_asse_asset_i_2f56b4_idx'), models.Index(fields=['event_type'], name='assets_asse_event_t_d5f08b_idx'), models.Index(fields=['event_date'], name='assets_asse_event_d_545eb8_idx'), models.Index(fields=['actor'], name='assets_asse_actor_i_81bdb7_idx')],
            },
        ),
    ]
