# Generated by Django 4.2.11 on 2026-04-23 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0004_assetevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(help_text='Reason for disposal')),
                ('disposal_method', models.CharField(choices=[('SALE', 'Sale'), ('DONATION', 'Donation'), ('SCRAP', 'Scrap'), ('DESTRUCTION', 'Destruction'), ('TRANSFER', 'Transfer to Another Institution')], max_length=20)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('committee_review_date', models.DateTimeField(blank=True, null=True)),
                ('committee_notes', models.TextField(blank=True)),
                ('committee_decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('manager_approval_date', models.DateTimeField(blank=True, null=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING_COMMITTEE', 'Pending Committee Review'), ('COMMITTEE_APPROVED', 'Committee Approved'), ('COMMITTEE_REJECTED', 'Committee Rejected'), ('PENDING_MANAGER', 'Pending Property Manager Approval'), ('APPROVED', 'Fully Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Disposal Completed')], default='PENDING_COMMITTEE', max_length=30)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_receipt', models.FileField(blank=True, null=True, upload_to='assets/disposal_receipts/')),
                ('final_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='AssetVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_date', models.DateField()),
                ('physical_condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('MISSING', 'Missing'), ('DAMAGED', 'Damaged')], max_length=20)),
                ('location_verified', models.BooleanField(default=True)),
                ('has_discrepancy', models.BooleanField(default=False)),
                ('discrepancy_type', models.CharField(blank=True, choices=[('LOCATION_MISMATCH', 'Location Mismatch'), ('CONDITION_MISMATCH', 'Condition Mismatch'), ('MISSING', 'Asset Missing'), ('UNAUTHORIZED_MODIFICATION', 'Unauthorized Modification'), ('OTHER', 'Other')], max_length=50)),
                ('discrepancy_description', models.TextField(blank=True)),
                ('discrepancy_reported_date', models.DateTimeField(blank=True, null=True)),
                ('discrepancy_report_deadline', models.DateField(blank=True, null=True)),
                ('discrepancy_report_submitted', models.BooleanField(default=False)),
                ('discrepancy_report_file', models.FileField(blank=True, null=True, upload_to='assets/verification_reports/')),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DISCREPANCY_FOUND', 'Discrepancy Found'), ('DISCREPANCY_RESOLVED', 'Discrepancy Resolved')], default='SCHEDULED', max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-verification_date'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='is_high_value',
            field=models.BooleanField(default=False, help_text='Asset value exceeds 10,000 ETB'),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_verification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='next_verification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='registration_deadline',
            field=models.DateField(blank=True, help_text='Deadline for registering assets >10,000 ETB', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='registration_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('DISCREPANCY', 'Discrepancy Found'), ('NOT_REQUIRED', 'Not Required')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED_SOURCE', 'Approved by Source Department'), ('APPROVED_DEST', 'Approved by Destination Department'), ('FULLY_APPROVED', 'Fully Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='dest_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='dest_department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dest_dept_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='source_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='source_department_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_dept_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('CONDEMNED', 'Condemned'), ('PENDING_DISPOSAL', 'Pending Disposal')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_high_value'], name='assets_asse_is_high_a0e8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['registration_deadline'], name='assets_asse_registr_15e07b_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['next_verification_date'], name='assets_asse_next_ve_4ec563_idx'),
        ),
        migrations.AddIndex(
            model_name='assettransfer',
            index=models.Index(fields=['asset', 'approval_status'], name='assets_asse_asset_i_1afdb0_idx'),
        ),
        migrations.AddIndex(
            model_name='assettransfer',
            index=models.Index(fields=['approval_status'], name='assets_asse_approva_afc81b_idx'),
        ),
        migrations.AddField(
            model_name='assetverification',
            name='actual_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_assets', to='assets.room'),
        ),
        migrations.AddField(
            model_name='assetverification',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetverification',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetverification',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposal_requests', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='committee_members',
            field=models.ManyToManyField(blank=True, related_name='disposal_committee_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='property_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='assetverification',
            index=models.Index(fields=['asset', 'verification_date'], name='assets_asse_asset_i_c50dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='assetverification',
            index=models.Index(fields=['status'], name='assets_asse_status_463f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='assetverification',
            index=models.Index(fields=['has_discrepancy'], name='assets_asse_has_dis_872c96_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdisposal',
            index=models.Index(fields=['asset', 'status'], name='assets_asse_asset_i_dd52f4_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdisposal',
            index=models.Index(fields=['status'], name='assets_asse_status_06e942_idx'),
        ),
    ]
