# Generated by Django 4.2.11 on 2026-04-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_assetdisposal_assetverification_asset_is_high_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdisposal',
            name='marked_for_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='retention_date',
            field=models.DateField(blank=True, help_text='Delete after this date (10 years)', null=True),
        ),
    ]
