# Generated by Django 4.2.11 on 2026-04-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_assetdisposal_marked_for_deletion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], default='GOOD', help_text='Physical condition of the asset', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Manufacturer or brand name', max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='model_number',
            field=models.CharField(blank=True, help_text='Model number or identifier', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Unique serial number', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.CharField(blank=True, help_text='Supplier or vendor name', max_length=200),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='assets_asse_serial__401a52_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['manufacturer'], name='assets_asse_manufac_839a8d_idx'),
        ),
    ]
