# Generated by Django 4.2.11 on 2026-04-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_asset_condition_asset_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdisposal',
            name='disposal_category',
            field=models.CharField(blank=True, choices=[('END_OF_LIFE', 'End of Life'), ('OBSOLETE', 'Obsolete'), ('DAMAGED_BEYOND_REPAIR', 'Damaged Beyond Repair'), ('SURPLUS', 'Surplus'), ('UPGRADE', 'Upgrade'), ('OTHER', 'Other')], help_text='Category of disposal', max_length=30),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='documentation',
            field=models.TextField(blank=True, help_text='Additional documentation or notes'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='environmental_impact',
            field=models.TextField(blank=True, help_text='Environmental impact assessment'),
        ),
        migrations.AddField(
            model_name='assetdisposal',
            name='planned_disposal_date',
            field=models.DateField(blank=True, help_text='Planned date for disposal', null=True),
        ),
    ]
