# Generated by Django 4.2.11 on 2026-04-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_checkoutextensionrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='checkoutextensionrequest',
            new_name='assets_chec_checkou_1a081e_idx',
            old_name='assets_chec_checkou_idx',
        ),
        migrations.RenameIndex(
            model_name='checkoutextensionrequest',
            new_name='assets_chec_status_0172b7_idx',
            old_name='assets_chec_status_idx',
        ),
        migrations.RenameIndex(
            model_name='checkoutextensionrequest',
            new_name='assets_chec_request_7b6c32_idx',
            old_name='assets_chec_request_idx',
        ),
    ]
