# Generated by Django 4.2.11 on 2026-05-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_asset_assignment_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assetassignmentrequest',
            new_name='assets_asse_request_681fb7_idx',
            old_name='assets_asse_request_idx',
        ),
        migrations.RenameIndex(
            model_name='assetassignmentrequest',
            new_name='assets_asse_status_178289_idx',
            old_name='assets_asse_status_idx',
        ),
        migrations.RenameIndex(
            model_name='assetassignmentrequest',
            new_name='assets_asse_request_697a98_idx',
            old_name='assets_asse_req_by_status_idx',
        ),
        migrations.RenameIndex(
            model_name='assetassignmentrequest',
            new_name='assets_asse_asset_i_603a94_idx',
            old_name='assets_asse_asset_status_idx',
        ),
        migrations.RenameIndex(
            model_name='assetassignmentrequest',
            new_name='assets_asse_priorit_d8c2a6_idx',
            old_name='assets_asse_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='assetassignmentrequest',
            new_name='assets_asse_waitlis_3b9a0f_idx',
            old_name='assets_asse_waitlist_idx',
        ),
        migrations.RenameIndex(
            model_name='assetassignmentrequest',
            new_name='assets_asse_is_over_5b9e22_idx',
            old_name='assets_asse_overdue_idx',
        ),
        migrations.RenameIndex(
            model_name='assetwaitlist',
            new_name='assets_asse_asset_i_ec1e28_idx',
            old_name='assets_wait_asset_status_idx',
        ),
        migrations.RenameIndex(
            model_name='assetwaitlist',
            new_name='assets_asse_user_id_5a7651_idx',
            old_name='assets_wait_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='assetwaitlist',
            new_name='assets_asse_status_230c1a_idx',
            old_name='assets_wait_deadline_idx',
        ),
        migrations.RenameIndex(
            model_name='assignmentrequesthistory',
            new_name='assets_assi_request_7b5923_idx',
            old_name='assets_hist_request_idx',
        ),
        migrations.RenameIndex(
            model_name='assignmentrequesthistory',
            new_name='assets_assi_action_5cb643_idx',
            old_name='assets_hist_action_idx',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='is_requestable',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='max_assignment_days',
        ),
    ]
