# Generated by Django 4.2.11 on 2026-05-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_rename_assets_asse_request_idx_assets_asse_request_681fb7_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetevent',
            name='event_type',
            field=models.CharField(choices=[('CHECKOUT', 'Checkout'), ('RETURN', 'Return'), ('CHECKED_IN', 'Checked In'), ('RETURN_INITIATED', 'Return Initiated'), ('MAINTENANCE_REQUEST', 'Maintenance Request'), ('MAINTENANCE_COMPLETE', 'Maintenance Complete'), ('CONDITION_CHANGE', 'Condition Change'), ('TRANSFER', 'Transfer'), ('ASSIGNMENT', 'Assignment')], max_length=30),
        ),
    ]
