# Generated by Django 4.2.11 on 2026-05-13 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0013_alter_assetevent_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extension_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('current_end_date', models.DateField(help_text='Current assignment end date')),
                ('requested_new_end_date', models.DateField(help_text='Requested new end date')),
                ('extension_days', models.PositiveIntegerField(help_text='Number of days requested')),
                ('reason', models.TextField(help_text='Why extension is needed')),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_end_date', models.DateField(blank=True, null=True)),
                ('approved_days', models.PositiveIntegerField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='assets.assetassignmentrequest')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_extensions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
                'indexes': [models.Index(fields=['extension_id'], name='assets_assi_extensi_e07858_idx'), models.Index(fields=['assignment', 'status'], name='assets_assi_assignm_205cd0_idx'), models.Index(fields=['requested_by', 'status'], name='assets_assi_request_30430e_idx'), models.Index(fields=['status', 'request_date'], name='assets_assi_status_8a0cf8_idx')],
            },
        ),
    ]
