# Generated by Django 4.2.11 on 2026-05-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_assignmentextensionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransfer',
            name='dest_approval_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='reason_category',
            field=models.CharField(blank=True, choices=[('DEPT_RELOCATION', 'Department Relocation'), ('SPACE_OPTIMIZATION', 'Space Optimization'), ('MAINTENANCE', 'Maintenance Requirements'), ('USER_REQUEST', 'User Request'), ('EQUIPMENT_UPGRADE', 'Equipment Upgrade'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Planned transfer date', null=True),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='source_approval_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Special handling requirements'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transfer_type',
            field=models.CharField(choices=[('PERMANENT', 'Permanent Transfer'), ('TEMPORARY', 'Temporary Transfer'), ('EMERGENCY', 'Emergency Transfer')], default='PERMANENT', max_length=20),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transportation_method',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual Carry'), ('CART', 'Cart/Trolley'), ('VEHICLE', 'Vehicle Transport'), ('PROFESSIONAL', 'Professional Movers')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='assettransfer',
            index=models.Index(fields=['transfer_type'], name='assets_asse_transfe_8d513f_idx'),
        ),
        migrations.AddIndex(
            model_name='assettransfer',
            index=models.Index(fields=['scheduled_date'], name='assets_asse_schedul_93fe02_idx'),
        ),
    ]
