# Generated by Django 4.2.11 on 2026-05-14 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0015_assettransfer_dest_approval_deadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assettransfer',
            old_name='dest_approval_deadline',
            new_name='completed_date',
        ),
        migrations.RemoveField(
            model_name='assettransfer',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='assettransfer',
            name='dest_approved_at',
        ),
        migrations.RemoveField(
            model_name='assettransfer',
            name='dest_department_head',
        ),
        migrations.RemoveField(
            model_name='assettransfer',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='assettransfer',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='assettransfer',
            name='source_approval_deadline',
        ),
        migrations.RemoveField(
            model_name='assettransfer',
            name='source_approved_at',
        ),
        migrations.RemoveField(
            model_name='assettransfer',
            name='source_department_head',
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or observations'),
        ),
        migrations.AddField(
            model_name='assettransfer',
            name='transferred_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assettransfer',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Transfer'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
