# Generated by Django 4.2.11 on 2026-05-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_simplify_asset_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetdisposal',
            name='documentation_file',
            field=models.FileField(blank=True, help_text='Supporting documents for disposal', null=True, upload_to='assets/disposal_docs/'),
        ),
    ]
