# Generated by Django 4.2.11 on 2026-05-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_assetdisposal_documentation_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetverification',
            name='verification_certificate',
            field=models.FileField(blank=True, null=True, upload_to='assets/verification_certificates/'),
        ),
    ]
