# Generated by Django 4.2.11 on 2026-05-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_assetverification_verification_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetdisposal',
            name='committee_decision',
        ),
        migrations.RemoveField(
            model_name='assetdisposal',
            name='committee_members',
        ),
        migrations.RemoveField(
            model_name='assetdisposal',
            name='committee_notes',
        ),
        migrations.RemoveField(
            model_name='assetdisposal',
            name='committee_review_date',
        ),
        migrations.AlterField(
            model_name='assetdisposal',
            name='status',
            field=models.CharField(choices=[('PENDING_MANAGER', 'Pending Property Manager Approval'), ('APPROVED', 'Fully Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Disposal Completed')], default='PENDING_MANAGER', max_length=30),
        ),
    ]
