# Generated by Django 4.2.11 on 2026-04-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_campus',
            field=models.CharField(blank=True, help_text='Primary campus assignment', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, choices=[('ELECTRICAL', 'Electrical'), ('PLUMBING', 'Plumbing'), ('HVAC', 'HVAC'), ('STRUCTURAL', 'Structural'), ('EQUIPMENT', 'Equipment Repair'), ('GENERAL', 'General Maintenance')], help_text='Primary specialization for maintenance technicians', max_length=20),
        ),
    ]
