# Generated by Django 4.2.11 on 2026-04-23 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_securityalert_usersession_user_auto_disabled_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('shift_type', models.CharField(choices=[('MORNING', 'Morning (8AM-4PM)'), ('AFTERNOON', 'Afternoon (12PM-8PM)'), ('EVENING', 'Evening (4PM-12AM)'), ('NIGHT', 'Night (8PM-8AM)'), ('FULL_DAY', 'Full Day (8AM-5PM)')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'MAINTENANCE_TECHNICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['technician', 'day_of_week'], name='users_techn_technic_dd4a34_idx'), models.Index(fields=['is_active'], name='users_techn_is_acti_58ce14_idx')],
                'unique_together': {('technician', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='TechnicianAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_LEAVE', 'On Leave'), ('SICK_LEAVE', 'Sick Leave'), ('VACATION', 'Vacation'), ('TRAINING', 'Training'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_availability', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'MAINTENANCE_TECHNICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Technician Availabilities',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['technician', 'start_date', 'end_date'], name='users_techn_technic_e55d25_idx'), models.Index(fields=['status'], name='users_techn_status_08ab41_idx')],
            },
        ),
    ]
