# Generated by Django 4.2.11 on 2026-04-28 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_technicianshift_technicianavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for failure', max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-attempt_time'],
                'indexes': [models.Index(fields=['username', 'ip_address'], name='users_faile_usernam_3cbe07_idx'), models.Index(fields=['attempt_time'], name='users_faile_attempt_827614_idx')],
            },
        ),
        migrations.CreateModel(
            name='IPAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(help_text='IP address, CIDR notation, or IP range', max_length=100)),
                ('list_type', models.CharField(choices=[('WHITELIST', 'Whitelist'), ('BLACKLIST', 'Blacklist')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('block_count', models.IntegerField(default=0, help_text='Number of times this rule blocked access')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_ip_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IP Access Control',
                'verbose_name_plural': 'IP Access Controls',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['list_type', 'is_active'], name='users_ipacc_list_ty_1f0de7_idx'), models.Index(fields=['ip_address'], name='users_ipacc_ip_addr_0e34a2_idx')],
            },
        ),
    ]
