# Generated by Django 4.2.11 on 2026-05-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_failedloginattempt_ipaccesscontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='performance_score',
            field=models.FloatField(default=0.0, help_text='Auto-calculated average score from service ratings (0-100)'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_ratings',
            field=models.IntegerField(default=0, help_text='Total number of ratings received'),
        ),
    ]
