# Generated by Django 4.2.11 on 2026-05-06 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_technician_performance_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'MAINTENANCE_TECHNICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clock_in'],
                'indexes': [models.Index(fields=['technician', 'clock_in'], name='users_timee_technic_a4c21c_idx'), models.Index(fields=['status'], name='users_timee_status_5934a3_idx')],
            },
        ),
    ]
