# Generated by Django 4.2.11 on 2026-05-06 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_time_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('emergency_responder', '🚨 Emergency Responder'), ('five_star', '⭐ 5-Star Technician'), ('speed_demon', '⚡ Speed Demon'), ('reliable', '🏆 Reliable'), ('century_club', '💯 Century Club'), ('first_complete', '🎯 First Complete'), ('team_player', '🤝 Team Player'), ('veteran', '🎖 Veteran')], max_length=30)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'MAINTENANCE_TECHNICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
                'unique_together': {('technician', 'badge_type')},
            },
        ),
    ]
