# Generated by Django 4.2.11 on 2026-05-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_technician_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='Backup codes for 2FA recovery'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_fa_enabled',
            field=models.BooleanField(default=False, help_text='Whether 2FA is enabled for this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_fa_enabled_at',
            field=models.DateTimeField(blank=True, help_text='When 2FA was enabled', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_fa_method',
            field=models.CharField(blank=True, choices=[('TOTP', 'Authenticator App'), ('SMS', 'SMS')], default='TOTP', help_text='2FA method', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='two_fa_secret',
            field=models.CharField(blank=True, help_text='TOTP secret key', max_length=32),
        ),
    ]
