# Generated by Django 4.2.11 on 2026-05-14 18:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_backup_codes_user_two_fa_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('strengths_template', models.TextField(blank=True)),
                ('improvement_template', models.TextField(blank=True)),
                ('goals_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_period_start', models.DateField()),
                ('review_period_end', models.DateField()),
                ('quality_of_work', models.IntegerField(help_text='Quality and accuracy of work performed', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeliness', models.IntegerField(help_text='Ability to complete tasks on time', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.IntegerField(help_text='Communication with team and requesters', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism', models.IntegerField(help_text='Professional conduct and attitude', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('technical_skills', models.IntegerField(help_text='Technical expertise and problem-solving', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('teamwork', models.IntegerField(help_text='Collaboration and teamwork', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_rating', models.FloatField(editable=False)),
                ('strengths', models.TextField(blank=True, help_text='Key strengths and achievements')),
                ('areas_for_improvement', models.TextField(blank=True, help_text='Areas needing improvement')),
                ('comments', models.TextField(blank=True, help_text='Additional comments and feedback')),
                ('goals', models.TextField(blank=True, help_text='Goals for next review period')),
                ('work_orders_completed', models.IntegerField(default=0)),
                ('avg_completion_time_hours', models.FloatField(default=0)),
                ('sla_compliance_rate', models.FloatField(default=0, help_text='Percentage')),
                ('customer_satisfaction_avg', models.FloatField(default=0, help_text='Average rating from service ratings')),
                ('technician_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('technician_comments', models.TextField(blank=True, help_text="Technician's response to review")),
                ('reviewer', models.ForeignKey(limit_choices_to={'role__in': ['MAINTENANCE_SUPERVISOR', 'PROPERTY_MANAGER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'MAINTENANCE_TECHNICIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['technician', '-created_at'], name='users_perfo_technic_b16646_idx'), models.Index(fields=['reviewer'], name='users_perfo_reviewe_2d81d3_idx'), models.Index(fields=['review_period_start', 'review_period_end'], name='users_perfo_review__9dd790_idx')],
                'unique_together': {('technician', 'review_period_start', 'review_period_end')},
            },
        ),
    ]
