# Generated by Django 4.2.11 on 2026-05-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_performance_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certifications',
            field=models.TextField(blank=True, help_text='List of certifications, licenses, and qualifications'),
        ),
    ]
