# Generated by Django 4.2.11 on 2026-05-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Uploaded certificate document', null=True, upload_to='users/certificates/'),
        ),
    ]
