# Generated by Django 4.2.11 on 2026-04-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_name', models.CharField(default='DMU Property Management System', max_length=200)),
                ('system_email', models.EmailField(default='admin@dmu.edu.et', max_length=254)),
                ('timezone', models.CharField(default='Africa/Addis_Ababa', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('sla_emergency', models.IntegerField(default=24, help_text='SLA for emergency requests in hours')),
                ('sla_high', models.IntegerField(default=72, help_text='SLA for high priority requests in hours')),
                ('sla_medium', models.IntegerField(default=168, help_text='SLA for medium priority requests in hours')),
                ('sla_low', models.IntegerField(default=336, help_text='SLA for low priority requests in hours')),
                ('auto_assignment', models.BooleanField(default=True, help_text='Enable automatic technician assignment')),
                ('preventive_maintenance', models.BooleanField(default=True, help_text='Enable preventive maintenance scheduling')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('notify_on_create', models.BooleanField(default=True)),
                ('notify_on_assign', models.BooleanField(default=True)),
                ('notify_on_complete', models.BooleanField(default=True)),
                ('notify_on_overdue', models.BooleanField(default=True)),
                ('password_min_length', models.IntegerField(default=8)),
                ('password_require_uppercase', models.BooleanField(default=True)),
                ('password_require_numbers', models.BooleanField(default=True)),
                ('password_require_special', models.BooleanField(default=True)),
                ('session_timeout', models.IntegerField(default=60, help_text='Session timeout in minutes')),
                ('max_login_attempts', models.IntegerField(default=5)),
                ('max_image_size', models.IntegerField(default=5, help_text='Maximum image size in MB')),
                ('max_report_size', models.IntegerField(default=10, help_text='Maximum report size in MB')),
                ('allowed_image_types', models.CharField(default='jpg, jpeg, png, gif', max_length=100)),
                ('allowed_report_types', models.CharField(default='pdf, doc, docx, xls, xlsx', max_length=100)),
                ('auto_backup', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('backup_retention', models.IntegerField(default=30, help_text='Backup retention period in days')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
