# Generated by Django 4.2.11 on 2026-04-17 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_databasebackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('maintenance_request', 'Maintenance Request'), ('work_order', 'Work Order'), ('asset_assignment', 'Asset Assignment'), ('request_overdue', 'Request Overdue'), ('request_completed', 'Request Completed'), ('status_change', 'Status Change'), ('system', 'System Notification')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, help_text='URL to navigate to when clicked', max_length=500)),
                ('read', models.BooleanField(default=False)),
                ('related_model', models.CharField(blank=True, max_length=100)),
                ('related_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='core_notifi_user_id_cb8d84_idx'), models.Index(fields=['user', '-created_at'], name='core_notifi_user_id_1cc5b6_idx')],
            },
        ),
    ]
