# Generated by Django 4.2.11 on 2026-04-20 07:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_initial'),
        ('assets', '0004_assetevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeliness_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quality_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_text', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('response_text', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('maintenance_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_rating', to='maintenance.maintenancerequest')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_ratings', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['maintenance_request'], name='core_servic_mainten_296ec1_idx'), models.Index(fields=['rated_by'], name='core_servic_rated_b_c61908_idx'), models.Index(fields=['overall_rating'], name='core_servic_overall_337d95_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortalSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('UI', 'User Interface'), ('FEATURES', 'Features'), ('PERFORMANCE', 'Performance'), ('MOBILE', 'Mobile Experience'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('screenshots', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('PLANNED', 'Planned'), ('IMPLEMENTED', 'Implemented'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('votes', models.IntegerField(default=0)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_suggestions', to=settings.AUTH_USER_MODEL)),
                ('voters', models.ManyToManyField(blank=True, related_name='voted_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-votes', '-created_at'],
                'indexes': [models.Index(fields=['submitted_by'], name='core_portal_submitt_e7c653_idx'), models.Index(fields=['status'], name='core_portal_status_863563_idx'), models.Index(fields=['category'], name='core_portal_categor_d76749_idx'), models.Index(fields=['-votes'], name='core_portal_votes_c80c0d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AssetFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_type', models.CharField(choices=[('CONDITION', 'Condition Issue'), ('REPLACEMENT', 'Replacement Suggestion'), ('MISSING_FEATURE', 'Missing Feature/Accessory'), ('GENERAL', 'General Feedback')], max_length=20)),
                ('description', models.TextField()),
                ('photos', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('response_text', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='assets.asset')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['asset'], name='core_assetf_asset_i_915ff6_idx'), models.Index(fields=['submitted_by'], name='core_assetf_submitt_50cbe1_idx'), models.Index(fields=['status'], name='core_assetf_status_1c7829_idx'), models.Index(fields=['feedback_type'], name='core_assetf_feedbac_c197a6_idx')],
            },
        ),
    ]
