# Generated by Django 4.2.11 on 2026-04-23 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='auto_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='escalated_to_department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='is_critical_equipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='max_delay_date',
            field=models.DateField(blank=True, help_text='Max 7-day delay for critical equipment', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='resolution_deadline',
            field=models.DateTimeField(blank=True, help_text='24-hour resolution for emergency', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='resolution_met',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='response_deadline',
            field=models.DateTimeField(blank=True, help_text='2-hour response for emergency', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='response_met',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='similar_issue_count',
            field=models.IntegerField(default=0, help_text='Count of similar issues in 30 days'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='contractor_license',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='contractor_license_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='contractor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workorder',
            name='finance_approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='finance_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='finance_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='fully_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='requester_signed_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='requester_signoff_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requester_signoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='requester_signoff_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='requires_finance_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='supervisor_signed_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='supervisor_signoff_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_signoffs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='supervisor_signoff_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='uses_external_contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='vendor_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['is_critical_equipment'], name='maintenance_is_crit_bb2af4_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerequest',
            index=models.Index(fields=['auto_escalated'], name='maintenance_auto_es_8d9eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['requires_finance_approval', 'finance_approved'], name='maintenance_require_5f3b81_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['fully_approved'], name='maintenance_fully_a_0f9ce1_idx'),
        ),
    ]
