# Generated by Django 4.2.11 on 2026-04-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancerequest_auto_escalated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='marked_for_deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='retention_date',
            field=models.DateField(blank=True, help_text='Delete after this date (7 years)', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='scheduled_for_next_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='submitted_after_hours',
            field=models.BooleanField(default=False, help_text='Submitted between 6PM-8AM'),
        ),
    ]
