# Generated by Django 4.2.11 on 2026-04-23 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0004_maintenancerequest_marked_for_deletion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLATracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_sla_hours', models.IntegerField(help_text='Expected response time in hours')),
                ('response_deadline', models.DateTimeField()),
                ('response_time', models.DateTimeField(blank=True, null=True)),
                ('response_met', models.BooleanField(default=False)),
                ('response_delay_hours', models.FloatField(default=0)),
                ('resolution_sla_hours', models.IntegerField(help_text='Expected resolution time in hours')),
                ('resolution_deadline', models.DateTimeField()),
                ('resolution_time', models.DateTimeField(blank=True, null=True)),
                ('resolution_met', models.BooleanField(default=False)),
                ('resolution_delay_hours', models.FloatField(default=0)),
                ('escalated', models.BooleanField(default=False)),
                ('escalation_reason', models.TextField(blank=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_requests', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sla_tracking', to='maintenance.maintenancerequest')),
            ],
            options={
                'verbose_name': 'SLA Tracking',
                'verbose_name_plural': 'SLA Tracking',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['response_met', 'resolution_met'], name='maintenance_respons_c3d7c4_idx'), models.Index(fields=['response_deadline'], name='maintenance_respons_3dca64_idx'), models.Index(fields=['resolution_deadline'], name='maintenance_resolut_52eca3_idx')],
            },
        ),
        migrations.CreateModel(
            name='RequestReassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('WORKLOAD', 'Workload Balancing'), ('SPECIALIZATION', 'Specialization Mismatch'), ('UNAVAILABLE', 'Technician Unavailable'), ('PERFORMANCE', 'Performance Issues'), ('EMERGENCY', 'Emergency Reassignment'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reassigned_at', models.DateTimeField(auto_now_add=True)),
                ('from_technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments_from', to=settings.AUTH_USER_MODEL)),
                ('reassigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments_made', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments', to='maintenance.maintenancerequest')),
                ('to_technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reassigned_at'],
                'indexes': [models.Index(fields=['request'], name='maintenance_request_5d687f_idx'), models.Index(fields=['from_technician'], name='maintenance_from_te_b8b4b1_idx'), models.Index(fields=['to_technician'], name='maintenance_to_tech_a62d8d_idx'), models.Index(fields=['reassigned_at'], name='maintenance_reassig_bf1f82_idx')],
            },
        ),
    ]
