# Generated by Django 4.2.11 on 2026-05-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_inventoryitem_partsrequest_stocktransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='estimated_hours',
            field=models.FloatField(blank=True, help_text='Estimated hours to complete', null=True),
        ),
    ]
