# Generated by Django 4.2.11 on 2026-05-09 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_team_communication'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='announcementread',
            new_name='maintenance_user_id_48c706_idx',
            old_name='maintenance_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='teamannouncement',
            new_name='maintenance_is_pinn_7c3308_idx',
            old_name='maintenance_is_pinn_idx',
        ),
        migrations.RenameIndex(
            model_name='teamannouncement',
            new_name='maintenance_is_acti_115b1c_idx',
            old_name='maintenance_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='teamconversation',
            new_name='maintenance_partici_7fe3c8_idx',
            old_name='maintenance_partici_idx',
        ),
        migrations.RenameIndex(
            model_name='teamconversation',
            new_name='maintenance_partici_4a0dcd_idx',
            old_name='maintenance_partici_idx2',
        ),
        migrations.RenameIndex(
            model_name='teammessage',
            new_name='maintenance_sender__1910bd_idx',
            old_name='maintenance_sender_idx',
        ),
        migrations.RenameIndex(
            model_name='teammessage',
            new_name='maintenance_recipie_9a0307_idx',
            old_name='maintenance_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='teammessage',
            new_name='maintenance_message_04e0af_idx',
            old_name='maintenance_message_idx',
        ),
    ]
