# Generated by Django 4.2.11 on 2026-05-15 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_rename_maintenance_user_id_idx_maintenance_user_id_48c706_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_file', models.FileField(help_text='Receipt image or PDF', upload_to='work_orders/receipts/%Y/%m/')),
                ('receipt_number', models.CharField(blank=True, help_text='Receipt/invoice number', max_length=100)),
                ('vendor_name', models.CharField(help_text='Vendor/supplier name', max_length=200)),
                ('purchase_date', models.DateField(help_text='Date of purchase')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount on receipt in ETB', max_digits=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the receipt')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material_name', models.CharField(help_text='Name/description of material', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity used', max_digits=10)),
                ('unit', models.CharField(default='pcs', help_text='Unit of measurement (pcs, kg, m, etc.)', max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Cost per unit in ETB', max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost (quantity × unit_cost)', max_digits=10)),
                ('supplier', models.CharField(blank=True, help_text='Supplier/vendor name', max_length=200)),
                ('part_number', models.CharField(blank=True, help_text='Part/catalog number', max_length=100)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='maintenance.workorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
