# Generated by Django 4.2.11 on 2026-05-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_workorderreceipt_workordermaterial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderreceipt',
            name='work_order',
        ),
        migrations.DeleteModel(
            name='WorkOrderMaterial',
        ),
        migrations.DeleteModel(
            name='WorkOrderReceipt',
        ),
    ]
