# Generated by Django 4.2.11 on 2026-04-23 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('data', models.JSONField(default=dict, help_text='Report data in JSON format')),
                ('metrics', models.JSONField(default=dict, help_text='MTTR, First-Time Fix Rate, Cost Per Repair, etc.')),
                ('data_currency_disclaimer', models.TextField(default='Data is current as of report generation time. Asset and maintenance information may have changed since generation.')),
                ('follows_ethiopian_guidelines', models.BooleanField(default=True, help_text='BR-RC-02: Follows Ethiopian Federal Property Administration Guidelines')),
                ('guideline_reference', models.CharField(blank=True, help_text='Reference to specific guideline (e.g., Annex B, Section 3.2)', max_length=100)),
                ('file', models.FileField(blank=True, help_text='Generated report file (PDF, Excel, etc.)', null=True, upload_to='reports/generated/')),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON')], default='PDF', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('authorized_by', models.ForeignKey(blank=True, help_text='BR-RC-04: Authorization line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('ASSET_STATUS', 'Asset Status Summary'), ('MAINTENANCE_COST', 'Maintenance Cost Analysis'), ('ASSET_UTILIZATION', 'Asset Utilization'), ('PREVENTIVE_COMPLIANCE', 'Preventive Maintenance Compliance'), ('MONTHLY_ASSET', 'Monthly Asset Report'), ('AUDIT_TRAIL', 'Audit Trail Report')], max_length=30)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUALLY', 'Annually')], max_length=20)),
                ('recipient_emails', models.TextField(blank=True, help_text='Additional email addresses (comma-separated)')),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month for monthly reports (e.g., 5 for BR-RC-01)', null=True)),
                ('day_of_week', models.IntegerField(blank=True, help_text='Day of week for weekly reports (0=Monday, 6=Sunday)', null=True)),
                ('time_of_day', models.TimeField(default='08:00:00', help_text='Time to generate report')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Additional parameters for report generation')),
                ('is_compliance_required', models.BooleanField(default=False, help_text='BR-RC-02: Follows Ethiopian Federal Guidelines')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(help_text='Property Manager, Finance Director, University Auditor', related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], default='SENT', max_length=20)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_distributions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='reports.generatedreport')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('mean_time_to_repair', models.DecimalField(decimal_places=2, help_text='MTTR in hours', max_digits=10)),
                ('first_time_fix_rate', models.DecimalField(decimal_places=2, help_text='Percentage of issues fixed on first attempt', max_digits=5)),
                ('cost_per_repair', models.DecimalField(decimal_places=2, help_text='Average cost per repair in ETB', max_digits=12)),
                ('total_requests', models.IntegerField(default=0)),
                ('completed_requests', models.IntegerField(default=0)),
                ('overdue_requests', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metrics_by_category', models.JSONField(default=dict, help_text='Metrics broken down by maintenance category')),
                ('metrics_by_priority', models.JSONField(default=dict, help_text='Metrics broken down by priority level')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Maintenance Metrics',
                'ordering': ['-period_end'],
            },
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='scheduled_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.scheduledreport'),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='sent_to',
            field=models.ManyToManyField(blank=True, related_name='received_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['status', 'next_run'], name='reports_sch_status_71bf46_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['report_type'], name='reports_sch_report__47f5b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportdistribution',
            unique_together={('report', 'recipient')},
        ),
        migrations.AlterUniqueTogether(
            name='maintenancemetrics',
            unique_together={('period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['report_type', 'generated_at'], name='reports_gen_report__7f8afa_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['period_start', 'period_end'], name='reports_gen_period__5dcdd5_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['is_draft', 'is_archived'], name='reports_gen_is_draf_17bdeb_idx'),
        ),
    ]
