# Generated by Django 4.2.11 on 2026-04-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreport',
            name='time_of_day',
            field=models.TimeField(help_text='Time to generate report'),
        ),
    ]
